# 一.ndarray
## 1.ndarray的特性
### 多维性 和同质性（不同类型强制转化）

In [10]:
# 注意每一个md文档输入后，按shift+enter 运行
#  md中输入#要空一个，才能渲染
#  快捷建m    换成md文档

In [5]:
import numpy as np

In [33]:
arr2=np.array(3) #0维  
arr1=np.array([1,23,4,3])  #1维    一维的形状：（4，）
arr3=np.array([[23,45,4,5,6],[1,23,4,3,3]])   #2维



In [21]:
#同质化
arr4=np.array([1,3.2])
print(arr4)  #注意这里的输出同质化了

[1.  3.2]


In [15]:
#属性
print("数组的形状：几行几列：",arr1.shape)
print("数组的形状：几行几列：",arr3.shape)


print("数组的个数：",arr1.size)
print("数组的个数：",arr3.size)

print("数组的转置：",arr1.T)
print("数组的转置：",arr3.T)

数组的形状：几行几列： (4,)
数组的形状：几行几列： (2, 5)
数组的个数： 4
数组的个数： 10
数组的转置： [ 1 23  4  3]
数组的转置： [[23  1]
 [45 23]
 [ 4  4]
 [ 5  3]
 [ 6  3]]


## 2.ndarray的创建

In [ ]:
#1.np.array 

#copy
arr1=np.array([1,3,3,3],dtype=np.float64)
arr2=arr1.copy()
print(arr2)


[1. 3. 3. 3.]


In [77]:
#预定义形状

#2.全0



arr=np.zeros((2,3),dtype=int)   #注意这里传的第一个参数是形状
print(arr)


[[0 0 0]
 [0 0 0]]


In [ ]:
#3.全1
arr=np.ones((3,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#4和5基于数值范围生成

#4.arange 等差数列
arr=np.arange(1,11,2)  #参数依次是start end step
print(arr)


[1 3 5 7 9]


In [27]:
#5.等间隔数列  linspace第二个参数是闭区间
arr=np.linspace(0,10,3)   
print(arr)


[ 0.  5. 10.]


In [76]:
#6.生成指定范围的随机浮点数
arr=np.random.uniform(3,6,(2,3))
print(arr)

#7.生成指定范围区间的随机整数
arr=np.random.randint(3,30,(2,3))
print(arr)

[[3.46249674 3.88085231 3.82485331]
 [4.71598317 3.52418    4.31027638]]
[[25  7  7]
 [11 25  7]]


## 3.索引与切片

In [49]:
arr1=np.array([1,23,4,3])  #1维    一维的形状：（4，）
arr3=np.array([[23,45,4,5,6],[1,23,4,3,3]])   #2维

In [50]:
#一维数组索引与切片
print(arr1[0]) #索引
print(arr1[0:3])  #左闭右开   （索引）
print(arr1[(arr1>1) & (arr1<9)])  #布尔索引：支持 & | （在这里相当于and 和or）
#切片  
print(arr1[slice(0,3,2)])

1
[ 1 23  4]
[4 3]
[1 4]


In [51]:
#二维数组索引与切片
print(arr3[1,3])
print(arr3[1:,1:])
print(arr3[arr3>10])
#只要某一行的布尔索引
print(arr3[1][arr3[1]>3])


3
[[23  4  3  3]]
[23 45 23]
[23  4]


## 4.数学运算与广播

In [56]:
#数组与数组
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1**arr2)

[ 2  4  6  8 10]
[0 0 0 0 0]
[ 1  4  9 16 25]
[1. 1. 1. 1. 1.]
[   1    4   27  256 3125]


In [57]:
#数组与标量
arr1=np.array([1,2,3,4,5])
arr2=np.array([1,2,3,4,5])
print(arr1+3)
print(arr1-3)
print(arr1*3)
print(arr1/3)
print(arr1**3)

[4 5 6 7 8]
[-2 -1  0  1  2]
[ 3  6  9 12 15]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[  1   8  27  64 125]


In [ ]:
#广播机制：1.获取形状 2.是否可以广播
#同一维度：相同、1  （两个数组的形状都是相同的，或者两个里面有一个1）
a=np.array([1,3,4])  #*1*3
b=np.array([[4],[5],[6]])  #3*1

"""""
步骤：
1*3
3*1
符合维度要求

a
1 3 4 
1 3 4 
1 3 4 

b
4 4 4 
5 5 5
6 6 6
"""
print(a+b)
print(a*b)
print(a@b)  #这是 点积（·）
print(a*b)  #这是(*) 
 

[[ 5  7  8]
 [ 6  8  9]
 [ 7  9 10]]
[[ 4 12 16]
 [ 5 15 20]
 [ 6 18 24]]
[43]


## 5.聚合操作.

In [62]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr.sum())    # 55  求和
print(arr.mean())   # 5.5 平均值
print(arr.max())    # 10  最大值
print(arr.min())    # 1   最小值
print(arr.std())    # 2.8722813232690143 标准差

55
5.5
10
1
2.8722813232690143


In [63]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

print(arr2d.sum())    # 45  (1+2+3+4+5+6+7+8+9)
print(arr2d.mean())   # 5.0

print(arr2d.sum(axis=0))    # [12 15 18]  (每列求和)
print(arr2d.mean(axis=0))   # [4. 5. 6.]  (每列平均值)

print(arr2d.sum(axis=1))    # [6 15 24]  (每行求和)
print(arr2d.mean(axis=1))   # [2. 5. 8.] (每行平均值)

45
5.0
[12 15 18]
[4. 5. 6.]
[ 6 15 24]
[2. 5. 8.]


## 6.形状


In [ ]:
#reshape   
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)  # (6,)

# 改成 2行×3列
arr2d = arr.reshape(2, 3)
print(arr2d)

(6,)
[[1 2 3]
 [4 5 6]]


In [69]:
#flatten   
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d.shape)  # (2, 3)

# 展平成一维
arr1d = arr2d.flatten()
print(arr1d)        # [1 2 3 4 5 6]
print(arr1d.shape)  # (6,)

(2, 3)
[1 2 3 4 5 6]
(6,)
